const data = [
  {
    id: '1',
    name: 'HP ProBook 455',
    prise: '3250',
    year: '2021',
    manufacturer: 'HP',
    color: 'серебристый',
    cpu: 'AMD Ryzen',
    favorite: false,
  },
  {
    id: '2',
    name: 'ASUS VivoBook 14',
    prise: '1900',
    year: '2021',
    manufacturer: 'ASUS',
    color: 'черный',
    cpu: 'Intel Core',
    favorite: false,
  },
  {
    id: '3',
    name: 'Apple Macbook Air 13"',
    prise: '3250',
    year: '2020',
    manufacturer: 'Apple',
    color: 'серый',
    cpu: 'Apple M1',
    favorite: true,
  },
  {
    id: '4',
    name: 'HP 14s-dq',
    prise: '1500',
    year: '2021',
    manufacturer: 'HP',
    color: 'белый',
    cpu: 'Intel Pentium',
    favorite: false,
  },
  {
    id: '5',
    name: 'Lenovo IdeaPad Gaming 3',
    prise: '2400',
    year: '2021',
    manufacturer: 'Lenovo',
    color: 'черный',
    cpu: 'AMD Ryzen', 
    favorite: true,
  },
  {
    id: '6',
    name: 'ASUS TUF Gaming Dash F15',
    prise: '3700',
    year: '2021',
    manufacturer: 'ASUS',
    color: 'черный',
    cpu: 'Intel Core',
    favorite: false,
  },
  {
    id: '7',
    name: 'Lenovo Legion 5',
    prise: '4200',
    year: '2022',
    manufacturer: 'Lenovo',
    color: 'черный',
    cpu: 'AMD Ryzen',
    favorite: true,
  },
  {
    id: '8',
    name: 'Acer ConceptD 3',
    prise: '3300',
    year: '2020',
    manufacturer: 'Acer',
    color: 'белый',
    cpu: 'Intel Core',
    favorite: false,
  },
  {
    id: '9',
    name: 'Lenovo IdeaPad 3',
    prise: '1850',
    year: '2021',
    manufacturer: 'Lenovo',
    color: 'серый',
    cpu: 'AMD Ryzen',
    favorite: false,
  },
  {
    id: '10',
    name: 'Apple Macbook Pro 14" M1',
    prise: '9000',
    year: '2021',
    manufacturer: 'Apple',
    color: 'серебристый',
    cpu: 'Apple M1',
    favorite: false,
  },
  {
    id: '11',
    name: 'Acer Aspire 5',
    prise: '2370',
    year: '2021',
    manufacturer: 'Acer',
    color: 'серебристый',
    cpu: 'AMD Ryzen',
    favorite: true,
  },
  {
    id: '12',
    name: 'ASUS ZenBook 14',
    prise: '4300',
    year: '2022',
    manufacturer: 'ASUS',
    color: 'черный',
    cpu: 'AMD Ryzen',
    favorite: false,
  },
  {
    id: '13',
    name: 'Apple Macbook Pro 16" M1 Max',
    prise: '7000',
    year: '2021',
    manufacturer: 'Apple',
    color: 'серый',
    cpu: 'Apple M1',
    favorite: true,
  },
  {
    id: '14',
    name: 'Acer Aspire 3',
    prise: '2050',
    year: '2020',
    manufacturer: 'Acer',
    color: 'черный',
    cpu: 'Intel Core',
    favorite: true,
  },
  {
    id: '15',
    name: 'HP 255 G7',
    prise: '1370',
    year: '2019',
    manufacturer: 'HP',
    color: 'черный',
    cpu: 'AMD Ryzen',
    favorite: false,
  },
  {
    id: '16',
    name: 'Lenovo IdeaPad 330',
    prise: '1550',
    year: '2018',
    manufacturer: 'Lenovo',
    color: 'серебристый',
    cpu: 'Intel Pentium',
    favorite: false,
  },
  {
    id: '17',
    name: 'ASUS ASUSPro',
    prise: '1750',
    year: '2019',
    manufacturer: 'ASUS',
    color: 'черный',
    cpu: 'Intel Pentium',
    favorite: false,
  },
  {
    id: '18',
    name: 'Apple Macbook Pro 13" M1',
    prise: '4500',
    year: '2020',
    manufacturer: 'Apple',
    color: 'серый',
    cpu: 'Apple M1',
    favorite: false,
  },
];

export default data;
