const data = [
  {
    num: '1',
    name: 'HP ProBook 455',
    count: '3250',
    year: '2021',
    shape: 'HP',
    color: 'серебристый',
    size: 'AMD Ryzen',
    favorite: false,
  },
  {
    num: '2',
    name: 'ASUS VivoBook 14',
    count: '1900',
    year: '2021',
    shape: 'ASUS',
    color: 'черный',
    size: 'Intel Core',
    favorite: false,
  },
  {
    num: '3',
    name: 'Apple Macbook Air 13"',
    count: '3250',
    year: '2020',
    shape: 'Apple',
    color: 'серый',
    size: 'Apple M1',
    favorite: true,
  },
  {
    num: '4',
    name: 'HP 14s-dq',
    count: '1500',
    year: '2021',
    shape: 'HP',
    color: 'белый',
    size: 'Intel Pentium',
    favorite: false,
  },
  {
    num: '5',
    name: 'Lenovo IdeaPad Gaming 3',
    count: '2400',
    year: '2021',
    shape: 'Lenovo',
    color: 'черный',
    size: 'AMD Ryzen', 
    favorite: true,
  },
  {
    num: '6',
    name: 'ASUS TUF Gaming Dash F15',
    count: '3700',
    year: '2021',
    shape: 'ASUS',
    color: 'черный',
    size: 'Intel Core',
    favorite: false,
  },
  {
    num: '7',
    name: 'Lenovo Legion 5',
    count: '4200',
    year: '2022',
    shape: 'Lenovo',
    color: 'черный',
    size: 'AMD Ryzen',
    favorite: true,
  },
  {
    num: '8',
    name: 'Acer ConceptD 3',
    count: '3300',
    year: '2020',
    shape: 'Acer',
    color: 'белый',
    size: 'Intel Core',
    favorite: false,
  },
  {
    num: '9',
    name: 'Lenovo IdeaPad 3',
    count: '1850',
    year: '2021',
    shape: 'Lenovo',
    color: 'серый',
    size: 'AMD Ryzen',
    favorite: false,
  },
  {
    num: '10',
    name: 'Apple Macbook Pro 14" M1',
    count: '9000',
    year: '2021',
    shape: 'Apple',
    color: 'серебристый',
    size: 'Apple M1',
    favorite: false,
  },
  {
    num: '11',
    name: 'Acer Aspire 5',
    count: '2370',
    year: '2021',
    shape: 'Acer',
    color: 'серебристый',
    size: 'AMD Ryzen',
    favorite: true,
  },
  {
    num: '12',
    name: 'ASUS ZenBook 14',
    count: '4300',
    year: '2022',
    shape: 'ASUS',
    color: 'черный',
    size: 'AMD Ryzen',
    favorite: false,
  },
  {
    num: '13',
    name: 'Apple Macbook Pro 16" M1 Max',
    count: '7000',
    year: '2021',
    shape: 'Apple',
    color: 'серый',
    size: 'Apple M1',
    favorite: true,
  },
  {
    num: '14',
    name: 'Acer Aspire 3',
    count: '2050',
    year: '2020',
    shape: 'Acer',
    color: 'черный',
    size: 'Intel Core',
    favorite: true,
  },
  {
    num: '15',
    name: 'HP 255 G7',
    count: '1370',
    year: '2019',
    shape: 'HP',
    color: 'черный',
    size: 'AMD Ryzen',
    favorite: false,
  },
  {
    num: '16',
    name: 'Lenovo IdeaPad 330',
    count: '1550',
    year: '2018',
    shape: 'Lenovo',
    color: 'серебристый',
    size: 'Intel Pentium',
    favorite: false,
  },
  {
    num: '17',
    name: 'ASUS ASUSPro',
    count: '1750',
    year: '2019',
    shape: 'ASUS',
    color: 'черный',
    size: 'Intel Pentium',
    favorite: false,
  },
  {
    num: '18',
    name: 'Apple Macbook Pro 13" M1',
    count: '4500',
    year: '2020',
    shape: 'Apple',
    color: 'серый',
    size: 'Apple M1',
    favorite: false,
  },
];

export default data;
